db:
  image: kartoza/postgis:9.4-2.1
  environment:
    - USERNAME=docker
    - PASS=docker
  
geoserver:
  #image: kartoza/geoserver
  build: ./
  hostname: geoserver
  volumes:
    # Wherever you want to mount your data from
    - ./data:/opt/geoserver/data_dir
    - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
  links:
    - db:db
  ports:
    - "8080:8080"
  environment:
    - USERNAME docker
    - PASS docker
